// 词包「好吃的!」(皮皮钦定首发,SPEC §4.2)
// 前 87 词沿袭 v0.1,ID/释义/例句不变(学习记录以 ID 为键);v0.2 补音标并扩充餐具与零食词

import { definePack, type Word } from './types'

const w = definePack('好吃的!', 1)

export const FOOD_WORDS: Word[] = [
  // —— 水果 ——
  w('apple', '/ˈæpl/', '苹果', '🍎', 'I eat an apple every day.', '我每天吃一个苹果。'),
  w('banana', '/bəˈnænə/', '香蕉', '🍌', 'The monkey loves bananas.', '猴子最爱香蕉。'),
  w('orange', '/ˈɔːrɪndʒ/', '橙子', '🍊', 'This orange is very sweet.', '这个橙子很甜。'),
  w('grape', '/ɡreɪp/', '葡萄', '🍇', 'Grapes are small and round.', '葡萄小小的、圆圆的。'),
  w('watermelon', '/ˈwɔːtərmelən/', '西瓜', '🍉', 'We eat watermelon in summer.', '我们夏天吃西瓜。'),
  w('strawberry', '/ˈstrɔːberi/', '草莓', '🍓', 'Strawberry cake is my favorite.', '草莓蛋糕是我的最爱。'),
  w('peach', '/piːtʃ/', '桃子', '🍑', 'The peach is soft and juicy.', '桃子又软又多汁。'),
  w('pear', '/per/', '梨', '🍐', 'Would you like a pear?', '你想要一个梨吗?'),
  w('lemon', '/ˈlemən/', '柠檬', '🍋', 'The lemon is very sour!', '柠檬好酸呀!'),
  w('mango', '/ˈmæŋɡoʊ/', '芒果', '🥭', 'Mango juice is yellow.', '芒果汁是黄色的。'),
  w('pineapple', '/ˈpaɪnæpl/', '菠萝', '🍍', 'A pineapple wears a spiky hat.', '菠萝戴着一顶刺刺的帽子。'),
  w('cherry', '/ˈtʃeri/', '樱桃', '🍒', 'Two cherries are on the cake.', '蛋糕上有两颗樱桃。'),
  w('kiwi', '/ˈkiːwiː/', '猕猴桃', '🥝', 'The kiwi is green inside.', '猕猴桃里面是绿色的。'),
  w('coconut', '/ˈkoʊkənʌt/', '椰子', '🥥', 'Coconut water is yummy.', '椰子水很好喝。'),
  w('blueberry', '/ˈbluːberi/', '蓝莓', '🫐', 'Blueberries make my tongue blue.', '蓝莓把我的舌头染蓝了。'),
  w('melon', '/ˈmelən/', '甜瓜', '🍈', 'This melon smells so good.', '这个甜瓜闻起来真香。'),
  w('avocado', '/ˌævəˈkɑːdoʊ/', '牛油果', '🥑', 'The avocado is green and soft.', '牛油果绿绿的、软软的。'),

  // —— 蔬菜 ——
  w('tomato', '/təˈmeɪtoʊ/', '西红柿', '🍅', 'Tomato and egg is a great dish.', '西红柿炒鸡蛋是道好菜。'),
  w('potato', '/pəˈteɪtoʊ/', '土豆', '🥔', 'French fries are made of potatoes.', '薯条是土豆做的。'),
  w('carrot', '/ˈkærət/', '胡萝卜', '🥕', 'Rabbits love carrots.', '兔子最爱胡萝卜。'),
  w('cucumber', '/ˈkjuːkʌmbər/', '黄瓜', '🥒', 'The cucumber is cool and crunchy.', '黄瓜凉凉的、脆脆的。'),
  w('corn', '/kɔːrn/', '玉米', '🌽', 'Sweet corn is my favorite vegetable.', '甜玉米是我最喜欢的蔬菜。'),
  w('pumpkin', '/ˈpʌmpkɪn/', '南瓜', '🎃', 'We made pumpkin soup.', '我们做了南瓜汤。'),
  w('mushroom', '/ˈmʌʃruːm/', '蘑菇', '🍄', 'Mushrooms grow after the rain.', '雨后长出了蘑菇。'),
  w('onion', '/ˈʌnjən/', '洋葱', '🧅', 'Onions make me cry.', '洋葱让我流眼泪。'),
  w('pepper', '/ˈpepər/', '辣椒', '🌶️', 'This red pepper is hot!', '这个红辣椒好辣!'),
  w('cabbage', '/ˈkæbɪdʒ/', '卷心菜', '🥬', 'The cabbage is big and round.', '卷心菜又大又圆。'),
  w('broccoli', '/ˈbrɑːkəli/', '西兰花', '🥦', 'Broccoli looks like a little tree.', '西兰花像一棵小树。'),
  w('garlic', '/ˈɡɑːrlɪk/', '大蒜', '🧄', 'Garlic keeps the vampires away.', '大蒜能吓跑吸血鬼。'),
  w('eggplant', '/ˈeɡplænt/', '茄子', '🍆', 'The eggplant is purple.', '茄子是紫色的。'),
  w('bean', '/biːn/', '豆子', '🫘', 'Jack has some magic beans.', '杰克有几颗魔法豆。'),

  // —— 饮料 ——
  w('water', '/ˈwɔːtər/', '水', '💧', 'Drink more water every day.', '每天要多喝水。'),
  w('milk', '/mɪlk/', '牛奶', '🥛', 'I drink milk before bed.', '我睡前喝牛奶。'),
  w('juice', '/dʒuːs/', '果汁', '🧃', 'Apple juice, please!', '请给我苹果汁!'),
  w('tea', '/tiː/', '茶', '🍵', 'Grandpa drinks tea every morning.', '爷爷每天早上喝茶。'),
  w('coffee', '/ˈkɔːfi/', '咖啡', '☕', 'Mom needs her coffee.', '妈妈需要她的咖啡。'),
  w('cola', '/ˈkoʊlə/', '可乐', '🥤', 'Cola has too much sugar.', '可乐糖太多啦。'),
  w('milkshake', '/ˈmɪlkʃeɪk/', '奶昔', '🍧', 'A strawberry milkshake, please.', '请来一杯草莓奶昔。'),

  // —— 食物 ——
  w('rice', '/raɪs/', '米饭', '🍚', 'We eat rice for dinner.', '我们晚饭吃米饭。'),
  w('noodles', '/ˈnuːdlz/', '面条', '🍜', 'I can eat noodles with chopsticks.', '我会用筷子吃面条。'),
  w('bread', '/bred/', '面包', '🍞', 'The bread is warm and soft.', '面包又热又软。'),
  // egg 的 F4 插图已获批准(egg-f4-v2);其余词的插图按 F4_WORD_ILLUSTRATION_POLICY 分批回填
  { ...w('egg', '/eɡ/', '鸡蛋', '🥚', 'The hen laid an egg!', '母鸡下了一个蛋!'), imageAssetId: 'egg-f4-v2' },
  w('cake', '/keɪk/', '蛋糕', '🍰', 'Happy birthday! Here is your cake.', '生日快乐!这是你的蛋糕。'),
  w('cookie', '/ˈkʊki/', '曲奇饼干', '🍪', 'Who ate my cookie?', '谁吃了我的曲奇?'),
  w('candy', '/ˈkændi/', '糖果', '🍬', 'Too much candy is bad for teeth.', '糖吃多了对牙齿不好。'),
  w('chocolate', '/ˈtʃɑːklət/', '巧克力', '🍫', 'Chocolate makes me happy.', '巧克力让我开心。'),
  w('ice cream', '/ˌaɪs ˈkriːm/', '冰淇淋', '🍦', 'Ice cream in winter? Yes!', '冬天吃冰淇淋?好呀!'),
  w('pizza', '/ˈpiːtsə/', '披萨', '🍕', 'Let us share this pizza.', '我们一起分这个披萨吧。'),
  w('hamburger', '/ˈhæmbɜːrɡər/', '汉堡包', '🍔', 'A big hamburger with cheese.', '一个加芝士的大汉堡。'),
  w('sandwich', '/ˈsænwɪtʃ/', '三明治', '🥪', 'I made a sandwich for the picnic.', '我为野餐做了一个三明治。'),
  w('hot dog', '/ˈhɑːt dɔːɡ/', '热狗', '🌭', 'A hot dog is not a real dog.', '热狗可不是真的狗。'),
  w('dumpling', '/ˈdʌmplɪŋ/', '饺子', '🥟', 'We make dumplings together.', '我们一起包饺子。'),
  w('fish', '/fɪʃ/', '鱼', '🐟', 'The cat wants my fish.', '猫咪想吃我的鱼。'),
  w('chicken', '/ˈtʃɪkɪn/', '鸡肉', '🍗', 'Fried chicken is crispy.', '炸鸡脆脆的。'),
  w('beef', '/biːf/', '牛肉', '🥩', 'Beef noodles are delicious.', '牛肉面真好吃。'),
  w('cheese', '/tʃiːz/', '芝士', '🧀', 'The mouse loves cheese.', '小老鼠最爱芝士。'),
  w('butter', '/ˈbʌtər/', '黄油', '🧈', 'Put some butter on the bread.', '在面包上抹点黄油。'),
  w('honey', '/ˈhʌni/', '蜂蜜', '🍯', 'Bears love honey.', '熊最爱蜂蜜。'),
  w('popcorn', '/ˈpɑːpkɔːrn/', '爆米花', '🍿', 'Popcorn and a movie!', '爆米花配电影!'),
  w('fries', '/fraɪz/', '薯条', '🍟', 'These fries are too salty.', '这些薯条太咸了。'),
  w('pancake', '/ˈpænkeɪk/', '松饼', '🥞', 'Pancakes with honey, yum!', '松饼配蜂蜜,好吃!'),
  w('pie', '/paɪ/', '派', '🥧', 'Grandma baked an apple pie.', '奶奶烤了一个苹果派。'),
  w('doughnut', '/ˈdoʊnʌt/', '甜甜圈', '🍩', 'The doughnut has a hole.', '甜甜圈有一个洞。'),
  w('sushi', '/ˈsuːʃi/', '寿司', '🍣', 'Sushi comes from Japan.', '寿司来自日本。'),
  w('ramen', '/ˈrɑːmən/', '拉面', '🍥', 'Ramen is Japanese noodles.', '拉面是日本的面条。'),
  w('soup', '/suːp/', '汤', '🍲', 'Drink your soup while it is hot.', '趁热喝汤。'),
  w('salad', '/ˈsæləd/', '沙拉', '🥗', 'A fruit salad is healthy.', '水果沙拉很健康。'),
  w('sausage', '/ˈsɔːsɪdʒ/', '香肠', '🌭', 'The dog stole a sausage.', '小狗偷了一根香肠。'),

  // —— 味道和吃喝 ——
  w('sweet', '/swiːt/', '甜的', '🍭', 'The candy is so sweet.', '这颗糖真甜。'),
  w('sour', '/ˈsaʊər/', '酸的', '😖', 'Lemons are sour.', '柠檬是酸的。'),
  w('salty', '/ˈsɔːlti/', '咸的', '🧂', 'Sea water is salty.', '海水是咸的。'),
  w('spicy', '/ˈspaɪsi/', '辣的', '🔥', 'This hot pot is too spicy!', '这个火锅太辣了!'),
  w('hot', '/hɑːt/', '热的;辣的', '♨️', 'Careful, the soup is hot!', '小心,汤是热的!'),
  w('cold', '/koʊld/', '冷的;凉的', '🧊', 'I want a cold drink.', '我想要一杯冷饮。'),
  w('delicious', '/dɪˈlɪʃəs/', '美味的', '😋', 'Dinner was delicious, Mom!', '妈妈,晚饭太好吃了!'),
  w('hungry', '/ˈhʌŋɡri/', '饿的', '🍽️', 'I am so hungry!', '我好饿呀!'),
  w('thirsty', '/ˈθɜːrsti/', '渴的', '💦', 'Running makes me thirsty.', '跑步让我口渴。'),
  w('eat', '/iːt/', '吃', '👄', 'Let us eat together.', '我们一起吃吧。'),
  w('drink', '/drɪŋk/', '喝', '🫗', 'Drink your milk, please.', '请把牛奶喝了。'),
  w('cook', '/kʊk/', '做饭', '👩‍🍳', 'Dad can cook noodles.', '爸爸会煮面条。'),
  w('breakfast', '/ˈbrekfəst/', '早餐', '🌅', 'Eggs for breakfast again?', '早餐又吃鸡蛋?'),
  w('lunch', '/lʌntʃ/', '午餐', '🍱', 'What is for lunch today?', '今天午餐吃什么?'),
  w('dinner', '/ˈdɪnər/', '晚餐', '🌙', 'Dinner is ready!', '晚餐好啦!'),
  w('snack', '/snæk/', '零食', '🍘', 'One snack after homework.', '写完作业吃一个零食。'),
  w('fruit', '/fruːt/', '水果', '🍎', 'Fruit is good for you.', '水果对你有好处。'),
  w('vegetable', '/ˈvedʒtəbl/', '蔬菜', '🥦', 'Eat your vegetables first.', '先把蔬菜吃了。'),
  w('yummy', '/ˈjʌmi/', '好吃的(口语)', '🤤', 'Yummy! I want more!', '真好吃!我还要!'),
  w('kitchen', '/ˈkɪtʃɪn/', '厨房', '🏠', 'Something smells good in the kitchen.', '厨房里有什么东西好香。'),

  // —— v0.2 扩充:肉蛋调料、餐具与零食(以下为新增,ID 同样一经发布不变) ——
  w('meat', '/miːt/', '肉', '🍖', 'We buy meat at the supermarket.', '我们在超市买肉。'),
  w('pork', '/pɔːrk/', '猪肉', '🥓', 'Dumplings with pork are yummy.', '猪肉馅的饺子真好吃。'),
  w('sugar', '/ˈʃʊɡər/', '糖(调味)', '🍬', 'Not too much sugar, please.', '请别放太多糖。'),
  w('salt', '/sɔːlt/', '盐', '🧂', 'Pass me the salt, please.', '请把盐递给我。'),
  w('oil', '/ɔɪl/', '油', '🫗', 'Mom cooks with a little oil.', '妈妈用一点油做菜。'),
  w('bowl', '/boʊl/', '碗', '🥣', 'A big bowl of rice, please.', '请来一大碗米饭。'),
  w('plate', '/pleɪt/', '盘子', '🍽️', 'The fish is on the plate.', '鱼在盘子里。'),
  w('cup', '/kʌp/', '杯子', '🥤', 'A cup of warm milk.', '一杯温牛奶。'),
  w('spoon', '/spuːn/', '勺子', '🥄', 'Eat the soup with a spoon.', '用勺子喝汤。'),
  w('fork', '/fɔːrk/', '叉子', '🍴', 'I eat cake with a fork.', '我用叉子吃蛋糕。'),
  w('knife', '/naɪf/', '刀', '🔪', 'The knife is sharp, be careful.', '刀很锋利,要小心。'),
  w('chopsticks', '/ˈtʃɑːpstɪks/', '筷子', '🥢', 'I can use chopsticks!', '我会用筷子啦!'),
  w('bottle', '/ˈbɑːtl/', '瓶子', '🍼', 'A bottle of orange juice.', '一瓶橙汁。'),
  w('jam', '/dʒæm/', '果酱', '🍓', 'Strawberry jam on warm bread.', '热面包配草莓酱。'),
  w('biscuit', '/ˈbɪskɪt/', '饼干', '🍪', 'One more biscuit, please!', '请再给我一块饼干!'),
  w('peanut', '/ˈpiːnʌt/', '花生', '🥜', 'The elephant likes peanuts.', '大象喜欢花生。'),
  w('yogurt', '/ˈjoʊɡərt/', '酸奶', '🥛', 'Blueberry yogurt is my favorite.', '蓝莓酸奶是我的最爱。'),
  w('pudding', '/ˈpʊdɪŋ/', '布丁', '🍮', 'The pudding shakes like jelly.', '布丁像果冻一样晃。'),
  w('jelly', '/ˈdʒeli/', '果冻', '🍮', 'The jelly is soft and cool.', '果冻又软又凉。'),
  w('taste', '/teɪst/', '尝一尝', '👅', 'Taste this soup, it is great.', '尝尝这个汤,棒极了。'),
  w('full', '/fʊl/', '吃饱的', '😌', 'I am full, thank you.', '我吃饱啦,谢谢。'),
  w('picnic', '/ˈpɪknɪk/', '野餐', '🧺', 'We have a picnic in the park.', '我们在公园野餐。'),
]
