// 词包「数字和时间」:数字、序数、星期、季节与时间词

import { definePack, type Word } from './types'

const w = definePack('数字和时间', 1)

export const NUMBER_TIME_WORDS: Word[] = [
  // —— 数字 ——
  w('one', '/wʌn/', '一', '1️⃣', 'I have one nose.', '我有一个鼻子。'),
  w('two', '/tuː/', '二', '2️⃣', 'I have two hands.', '我有两只手。'),
  w('three', '/θriː/', '三', '3️⃣', 'Three chicks are sleeping.', '三只小鸡在睡觉。'),
  w('four', '/fɔːr/', '四', '4️⃣', 'A cat has four legs.', '猫有四条腿。'),
  w('five', '/faɪv/', '五', '5️⃣', 'Give me five!', '击个掌!'),
  w('six', '/sɪks/', '六', '6️⃣', 'The ant has six legs.', '蚂蚁有六条腿。'),
  w('seven', '/ˈsevn/', '七', '7️⃣', 'A rainbow has seven colors.', '彩虹有七种颜色。'),
  w('eight', '/eɪt/', '八', '8️⃣', 'Spiders have eight legs.', '蜘蛛有八条腿。'),
  w('nine', '/naɪn/', '九', '9️⃣', 'It is nine, time for bed!', '九点了,该睡觉啦!'),
  w('ten', '/ten/', '十', '🔟', 'I have ten fingers.', '我有十根手指。'),
  w('eleven', '/ɪˈlevn/', '十一', '🕚', 'Eleven birds sit on the wire.', '十一只鸟停在电线上。'),
  w('twelve', '/twelv/', '十二', '🕛', 'A year has twelve months.', '一年有十二个月。'),
  w('thirteen', '/ˌθɜːrˈtiːn/', '十三', '🔢', 'Thirteen candies in the jar.', '罐子里有十三颗糖。'),
  w('fourteen', '/ˌfɔːrˈtiːn/', '十四', '🔢', 'My cousin is fourteen years old.', '我表哥十四岁。'),
  w('fifteen', '/ˌfɪfˈtiːn/', '十五', '🔢', 'Count from one to fifteen.', '从一数到十五。'),
  w('sixteen', '/ˌsɪksˈtiːn/', '十六', '🔢', 'The bus number is sixteen.', '这路公交是十六路。'),
  w('seventeen', '/ˌsevnˈtiːn/', '十七', '🔢', 'Seventeen stars, I counted!', '我数到了十七颗星星!'),
  w('eighteen', '/ˌeɪˈtiːn/', '十八', '🔢', 'Grandpa planted eighteen trees.', '爷爷种了十八棵树。'),
  w('nineteen', '/ˌnaɪnˈtiːn/', '十九', '🔢', 'Nineteen steps to my room.', '到我房间有十九级台阶。'),
  w('twenty', '/ˈtwenti/', '二十', '🔢', 'Twenty chicks live on the farm.', '农场里住着二十只小鸡。'),
  w('thirty', '/ˈθɜːrti/', '三十', '🔢', 'One month has about thirty days.', '一个月大约三十天。'),
  w('forty', '/ˈfɔːrti/', '四十', '🔢', 'Forty ants march in a line.', '四十只蚂蚁排队走。'),
  w('fifty', '/ˈfɪfti/', '五十', '🔢', 'This book has fifty pages.', '这本书有五十页。'),
  w('hundred', '/ˈhʌndrəd/', '一百', '💯', 'I can count to one hundred!', '我能数到一百!'),
  w('zero', '/ˈzɪroʊ/', '零', '0️⃣', 'Zero means nothing at all.', '零就是什么都没有。'),
  w('number', '/ˈnʌmbər/', '数字', '🧮', 'Pick a number from one to ten.', '从一到十挑一个数字。'),
  w('first', '/fɜːrst/', '第一', '🥇', 'I finished first in the race!', '我比赛得了第一!'),
  w('second', '/ˈsekənd/', '第二;秒', '🥈', 'The second egg hatched today.', '第二颗蛋今天孵化了。'),
  w('third', '/θɜːrd/', '第三', '🥉', 'My classroom is on the third floor.', '我的教室在三楼。'),
  // —— 天与星期 ——
  w('today', '/təˈdeɪ/', '今天', '📅', 'Today is a sunny day.', '今天是晴天。'),
  w('tomorrow', '/təˈmɑːroʊ/', '明天', '🌅', 'See you tomorrow!', '明天见!'),
  w('yesterday', '/ˈjestərdeɪ/', '昨天', '🗓️', 'Yesterday we made dumplings.', '昨天我们包了饺子。'),
  w('day', '/deɪ/', '天;白天', '☀️', 'What a beautiful day!', '多美好的一天!'),
  w('week', '/wiːk/', '星期;周', '🗓️', 'A week has seven days.', '一星期有七天。'),
  w('month', '/mʌnθ/', '月', '📆', 'My birthday month is May.', '我的生日在五月。'),
  w('year', '/jɪr/', '年', '🎆', 'Happy new year!', '新年快乐!'),
  w('Monday', '/ˈmʌndeɪ/', '星期一', '📅', 'Monday is a school day.', '星期一要上学。'),
  w('Tuesday', '/ˈtuːzdeɪ/', '星期二', '📅', 'We have art class on Tuesday.', '星期二有美术课。'),
  w('Wednesday', '/ˈwenzdeɪ/', '星期三', '📅', 'Wednesday is in the middle.', '星期三在一周的中间。'),
  w('Thursday', '/ˈθɜːrzdeɪ/', '星期四', '📅', 'It will rain on Thursday.', '星期四会下雨。'),
  w('Friday', '/ˈfraɪdeɪ/', '星期五', '📅', 'Friday is my favorite day.', '星期五是我最喜欢的一天。'),
  w('Saturday', '/ˈsætərdeɪ/', '星期六', '📅', 'We visit Grandma on Saturday.', '星期六我们去看奶奶。'),
  w('Sunday', '/ˈsʌndeɪ/', '星期天', '📅', 'Sunday is for sleeping in.', '星期天可以睡懒觉。'),
  w('weekend', '/ˈwiːkend/', '周末', '🎉', 'What a fun weekend!', '多开心的周末!'),
  // —— 时间 ——
  w('hour', '/ˈaʊər/', '小时', '⏳', 'We played for an hour.', '我们玩了一个小时。'),
  w('minute', '/ˈmɪnɪt/', '分钟', '⏱️', 'Wait a minute, please.', '请等一分钟。'),
  w('morning', '/ˈmɔːrnɪŋ/', '早上', '🌄', 'Good morning, little hen!', '早上好,小母鸡!'),
  w('afternoon', '/ˌæftərˈnuːn/', '下午', '🌤️', 'We play games in the afternoon.', '我们下午玩游戏。'),
  w('evening', '/ˈiːvnɪŋ/', '傍晚', '🌆', 'In the evening we take a walk.', '傍晚我们去散步。'),
  w('night', '/naɪt/', '夜晚', '🌃', 'Stars come out at night.', '星星在夜晚出现。'),
  w('noon', '/nuːn/', '中午', '🕛', 'We eat lunch at noon.', '我们中午吃午饭。'),
  w('time', '/taɪm/', '时间', '⌛', 'What time is it now?', '现在几点了?'),
  w('clock', '/klɑːk/', '钟', '⏰', 'The clock says eight.', '钟指着八点。'),
  w('birthday', '/ˈbɜːrθdeɪ/', '生日', '🎂', 'Happy birthday to you!', '祝你生日快乐!'),
  // —— 季节 ——
  w('season', '/ˈsiːzn/', '季节', '🍃', 'Which season do you like best?', '你最喜欢哪个季节?'),
  w('spring', '/sprɪŋ/', '春天', '🌷', 'Flowers bloom in spring.', '春天花儿开放。'),
  w('summer', '/ˈsʌmər/', '夏天', '⛱️', 'We swim in summer.', '我们夏天游泳。'),
  w('autumn', '/ˈɔːtəm/', '秋天', '🍂', 'Leaves fall in autumn.', '秋天叶子落下。'),
  w('winter', '/ˈwɪntər/', '冬天', '⛄', 'It snows in winter.', '冬天会下雪。'),
]
